#cloud-config

coreos:
  update:
    reboot-strategy: etcd-lock
  locksmith:
    group: k8s-minion
    endpoint: "http://127.0.0.1:2379"
  flannel:
    interface: $private_ipv4
    etcd_endpoints: "http://127.0.0.1:2379"
    etcd_prefix: ${flannel_etcd_prefix}
  etcd2:
    proxy: on
    discovery: "${discovery_url}"
    listen-client-urls: "http://127.0.0.1:2379"
  units:
    - name: etcd.service
      mask: true
    - name: etcd2.service
      command: "restart"
    - name: flanneld.service
      command: "restart"
    - name: copy-kubernetes-config-from-master.service
      command: "start"
      content: |
        [Service]
        Type=oneshot
        ExecStartPre=/usr/bin/mkdir -p /etc/kubernetes
        ExecStartPre=/usr/bin/ssh -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null \
          -i /home/core/.ssh/id_rsa core@${master_private_ip} \
          "while [ ! -f /home/core/assets/auth/kubeconfig ]; do echo 'Waiting for /home/core/assets/auth/kubeconfig...'; sleep 1; done"
        ExecStart=/usr/bin/scp -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null \
          -i /home/core/.ssh/id_rsa core@${master_private_ip}:/home/core/assets/auth/kubeconfig \
          /etc/kubernetes/kubeconfig
        ExecStartPost=/usr/bin/rm -f /home/core/.ssh/id_rsa
        RemainAfterExit=yes
    - name: kubelet.service
      command: "start"
      content: |
        [Unit]
        Requires=docker.service flanneld.service etcd2.service copy-kubernetes-config-from-master.service
        After=docker.service flanneld.service etcd2.service copy-kubernetes-config-from-master.service

        [Service]
        Environment=KUBELET_ACI=${kubelet_repo}
        Environment=KUBELET_VERSION=${kubelet_version}
        Environment="RKT_OPTS=--volume etc-resolv,kind=host,source=/etc/resolv.conf --mount volume=etc-resolv,target=/etc/resolv.conf"
        EnvironmentFile=/etc/environment

        ExecStartPre=/bin/mkdir -p /etc/kubernetes/manifests
        ExecStartPre=/usr/bin/sh -c "while [ ! -f /etc/kubernetes/kubeconfig ]; do \
            echo 'Waiting for /etc/kubernetes/kubeconfig...'; \
            sleep 1; \
          done"
        ExecStart=/usr/lib/coreos/kubelet-wrapper \
          --api-servers=https://${master_private_ip}:443 \
          --kubeconfig=/etc/kubernetes/kubeconfig \
          --lock-file=/var/run/lock/kubelet.lock \
          --exit-on-lock-contention \
          --allow-privileged \
          --hostname-override=$${COREOS_PRIVATE_IPV4} \
          --minimum-container-ttl-duration=3m0s \
          --cluster_dns=${kubelet_cluster_dns} \
          --cluster_domain=cluster.local \
          --config=/etc/kubernetes/manifests \
          --cloud-provider=aws

        Restart=always
        RestartSec=5

        [Install]
        WantedBy=multi-user.target
write_files:
  - path: /home/core/.ssh/id_rsa
    permissions: 0400
    owner: core:core
    encoding: base64
    content: ${aws_private_key}
