#cloud-config

coreos:
  update:
    reboot-strategy: etcd-lock
  etcd2:
    discovery: "${discovery_url}"
    listen-client-urls: "http://0.0.0.0:2379"
  units:
    - name: etcd.service
      mask: true
    - name: etcd2.service
      command: "start"
    - name: flanneld.service
      command: "start"
    - name: kubelet.service
      command: "start"
      content: |
        [Unit]
        Requires=docker.service flanneld.service
        After=docker.service flanneld.service

        [Service]
        Environment=KUBELET_ACI=${kubelet_repo}
        Environment=KUBELET_VERSION=${kubelet_version}
        Environment="RKT_OPTS=--volume etc-resolv,kind=host,source=/etc/resolv.conf --mount volume=etc-resolv,target=/etc/resolv.conf"
        EnvironmentFile=/etc/environment

        ExecStartPre=/bin/mkdir -p /etc/kubernetes/manifests
        ExecStart=/usr/lib/coreos/kubelet-wrapper \
          --api-servers=https://${master_private_ip}:443 \
          --kubeconfig=/etc/kubernetes/kubeconfig \
          --lock-file=/var/run/lock/kubelet.lock \
          --exit-on-lock-contention \
          --allow-privileged \
          --hostname-override=$${COREOS_PRIVATE_IPV4} \
          --minimum-container-ttl-duration=3m0s \
          --cluster_dns=${kubelet_cluster_dns} \
          --cluster_domain=cluster.local \
          --config=/etc/kubernetes/manifests

        Restart=always
        RestartSec=5

        [Install]
        WantedBy=multi-user.target
write_files:
  - path: /etc/kubernetes/kubeconfig
    permissions: 0644
    owner: root:root
    encoding: base64
    content: ${kubeconfig}
